### PR TITLE
Throw an exception if Catapult credentials are not set, and fix an error in the logs

### PR DESCRIPTION
**Pull request by ffranco-daitan**

### CODE REVIEW

**Comment by nadirhamid** [comment]
Hi Philippe,

If the catapult sdk needs to be used without the client. you would need to not specify it.
changing the credentials to be empty is not needed in my opinion.

**Comment by ffranco-daitan** [comment]
Hi @nadirhamid I've changed the credentials to be empty to make it easier to detect when they ar enot set.
Is there any case in which you would use the client without specifying credentials?

**Comment by nadirhamid** [comment]
Yes to generate BXML

for example:
once Catapult\Client is called credential search happens

without it using the BXML is possible

**Comment by dtolb** [comment]
@ffranco-daitan is this still valid

**Comment by ffranco-daitan** [comment]
I don't think it is, closing it!

**Pull request closed without merging**
